// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1.Data;

#nullable disable

namespace Task1.Migrations
{
    [DbContext(typeof(Task1DbContext))]
    [Migration("20240227090629_CreatedTableAndOneData")]
    partial class CreatedTableAndOneData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task1.Data.sampledata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSINESS_HOURS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BU_CODES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURRENCY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LATITUDE")
                        .HasColumnType("int");

                    b.Property<int>("LONGITUDE")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OPENED_DT")
                        .HasColumnType("date");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SampleData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ADDRESS = "19020   111th Ave",
                            BUSINESS_HOURS = "Monday - Friday 7:30am - 5:00pm",
                            BU_CODES = "AB100",
                            CITY = "EDMONTON",
                            COUNTRY_NAME = "Canada",
                            CURRENCY = "CAD",
                            LATITUDE = 54,
                            LONGITUDE = -114,
                            OPENED_DT = new DateOnly(2008, 9, 15),
                            PHONE = "780-801-5006",
                            STATE_NAME = "Alberta",
                            STATUS = "Open"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
